# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc_address', models.CharField(max_length=100)),
                ('uc_phone', models.CharField(max_length=15)),
                ('uc_zipcode', models.CharField(max_length=10)),
                ('uc_isDelete', models.BooleanField(default=False)),
                ('uc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.user_info1')),
            ],
        ),
    ]
